graph LR
    A["ManagedApplicationModule.Мсп_ПриНачалеРаботыСистемы"] --> B["CommonForm Мсп_УправлениеMCP"]
    B --> C["Мсп_Сервер.ЗапуститьСервер"]
    C --> D["Мсп_ТранспортСерверКлиент.ЗапуститьСервер"]
    D --> E["Мсп_ТранспортРеестрыКлиент.ИнициализироватьРеестрыСервера"]
    E --> F["Мсп_РеестрКлиент.ИнициализироватьРеестры"]
    E --> G["Мсп_ПровайдерыКлиент.ЗарегистрироватьПровайдеров"]
    G --> H["Мсп_МетаданныеСервер.Провайдеры"]
    G --> I["Провайдер: Мсп_ИнструментТестКлиент.ЗарегистрироватьИнструменты"]
    G --> J["Провайдер: Мсп_РесурсыТестКлиент.ЗарегистрироватьРесурсы"]
    E --> L["Мсп_ТранспортРеестрыКлиент.СинхронизироватьРеестрыСКомпонентой"]

    M["ManagedApplicationModule.Мсп_ОбработкаВнешнегоСобытия"] --> N["Мсп_ТранспортСобытияКлиент.ОбработатьВнешнееСобытие"]

    N --> O["Мсп_ТранспортСобытияКлиент.ОбработатьToolCall"]
    O --> P["Мсп_ПротоколКлиент.ВызватьИнструмент"]
    P --> Q["Мсп_РеестрКлиент.РеестрИнструментов"]
    P --> R["handler: test_client_start"]
    P --> S["handler: test_client_stop"]
    P --> T["handler: find"]
    P --> U["handler: activate"]
    P --> V["handler: click"]
    P --> W["handler: input"]
    P --> X["handler: select"]
    P --> Y["handler: close"]
    P --> Z["handler: open_form"]

    R --> R1["Мсп_УправлениеТестКлиентом.Запустить"]
    R1 --> R2["ЗапуститьТестКлиент"]
    R1 --> R3["Подключиться"]

    S --> S1["Мсп_УправлениеТестКлиентом.Остановить"]
    S1 --> S2["РазорватьСоединение"]

    T --> T1["Мсп_ФормыКлиент.НайтиОбъекты"]
    T1 --> T2["ПолучитьКореньПоиска"]
    T2 --> T3["Мсп_УправлениеТестКлиентом.ПолучитьТестКлиент"]

    U --> U1["Мсп_ФормыКлиент.АктивизироватьПоURI"]
    U1 --> U2["ПолучитьОбъектПоURI"]

    V --> V1["Мсп_ФормыКлиент.НажатьПоURI"]
    V1 --> V2["ПолучитьОбъектПоURI"]
    V1 --> V3["ПолучитьКонтекстДействия"]
    V3 --> V4["Мсп_ОкнаКлиент.АктивноеОкноПриложения"]

    W --> W1["Мсп_ФормыКлиент.ВвестиТекстПоURI"]
    W1 --> W2["ПолучитьОбъектПоURI"]
    W1 --> W3["ПолучитьКонтекстДействия"]

    X --> X1["Мсп_ФормыКлиент.ВыбратьПоURI"]
    X1 --> X2["ПолучитьОбъектПоURI"]
    X1 --> X3["ПолучитьРодительскуюФорму"]
    X1 --> X4["ПолучитьКонтекстДействия"]

    Y --> Y1["Мсп_ФормыКлиент.ЗакрытьПоURI"]
    Y1 --> Y2["Мсп_ОкнаКлиент.ОкноПоURI"]
    Y1 --> Y3["Мсп_ФормыКлиент.ФормаПоURI"]

    Z --> Z1["Мсп_ФормыКлиент.ОткрытьФормуПоКоманде"]
    Z1 --> Z2["Мсп_ОкнаКлиент.АктивноеОкноПриложения"]
    Z1 --> Z3["Мсп_ФормыКлиент.ПолучитьСписокФорм"]

    N --> AA["Мсп_ТранспортСобытияКлиент.ОбработатьResourceRead"]
    AA --> AB["Мсп_ПротоколКлиент.ПрочитатьРесурс"]
    AB --> AC["Мсп_РеестрКлиент.РеестрРесурсов"]
    AB --> AD["handler: Мсп_РесурсыТестКлиент.ОбработатьРесурсФормы"]
    AD --> AE["Мсп_ФормыКлиент.ФормаПоURI"]
